### ISSUE TITLE
the time provided by your paper including preprocess time / post-precess time or not?

### ISSUE THREAD

**Issue by kaixinbear** [Banconxuan/RTM3D#4]
![image](https://user-images.githubusercontent.com/33575107/77424254-c3fc2a00-6e0b-11ea-8fea-43ebebe31581.png)

**Comment by kaixinbear** [comment]
How is your time metric,including pre/post process time? Have you calculate time from cpu---gpu---cpu?
This is a very important question,which determines your core idea "real-time" lies or not！！！
It matters a lot!!! But you don't mention it on your paper.
 Could you please answer me?Thanks a lot.

**Comment by Banconxuan** [comment]
1. We report time including network forward time, decode time(just like [CenterNet](https://github.com/xingyizhou/CenterNet/issues/381)), and our geometry computing time.  

2. No cpu-gpu-cpu time is included. We believe this time is not reported in most methods with geometric constraint modules.
