### ISSUE TITLE
Unofficial repo?

### ISSUE THREAD

**Issue by wufeim** [Banconxuan/RTM3D#6]
Hi,

I found this Pytorch implementation of RTM3D: https://github.com/maudzung/RTM3D. Is this an unofficial implementation or if the official implementation is moved to that repo?

**Comment by maudzung** [comment]
Hi @wufeim 

It is my unofficial implementation with [several modifications](https://github.com/maudzung/RTM3D#some-modifications-from-the-paper). I have asked the author some questions [here](https://github.com/Banconxuan/RTM3D/issues/5).

**Comment by wufeim** [comment]
> Hi @wufeim
> 
> It is my unofficial implementation with [several modifications](https://github.com/maudzung/RTM3D#some-modifications-from-the-paper). I have asked the author some questions [here](https://github.com/Banconxuan/RTM3D/issues/5).

Thanks for the clarification. And thank you for your work! That is a great implementation and the code is clean and organized.
