### ISSUE TITLE
Annotation - COCO format

### ISSUE THREAD

**Issue by aungriah** [Banconxuan/RTM3D#7]
Thank you very much for sharing the code! 

Would it be possible to share the scripts used to convert the annotations to coco format?

**Comment by kaixinbear** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './kitti_format/data/kitti/annotations/kitti_val.json'

**Comment by kaixinbear** [comment]
create an folder  data/kitti/annotations and then run `python ./src/tools/kitti.py`

**Comment by aungriah** [comment]
Thank you @kaixinbear !
