### ISSUE TITLE
请教一下论文中的检测head的问题

### ISSUE THREAD

**Issue by chenjianqiang199526** [Banconxuan/RTM3D#9]
您好，我发现你的论文写的检测头的固定部分和可选的部分好像和代码不太一样，我想请教下如果是按论文中固定的检测头部分：中心点和关键点以及关键点的跟中心点的向量的话还能还原出3D bboxes吗？谢谢~

**Comment by Banconxuan** [comment]
只有keypoint的话没办法恢复，RTM3D的可选模块虽然可选，但至少需要选择一项，ablation study里有分析。

**Comment by chenjianqiang199526** [comment]
好的，我在仔细阅读下您的论文，要是还有什么问题再跟您探讨

**Comment by chenjianqiang199526** [comment]
大佬，再请教下如果没有物体的三维尺寸，只有orientation的话怎么还原出3D bboxes，我看ablation里面有一个实验是只有这个的

**Comment by Banconxuan** [comment]
RTM3D用的非线性优化库，ablation那个那个设成未知量就行。理论上只有orientation因为尺度不确定一般不会work，但是非线性库需要初始值，我们用到dataset的统计平均值作为初始值，所以也是有点效果的。

**Comment by chenjianqiang199526** [comment]
好的，明白了，谢谢
